test_csv:

features_dir:
output_dir: 'output/debug'
experiment_name: 'inference'
level: 'global'

task: 'survival'

label_name: 'label'
label_mapping:
label_encoding:
nbins:

model:
  checkpoint:
  dropout: 0.25
  embed_dim_patch: 384
  embed_dim_region: 192
  embed_dim_slide: 192
  region_size: 4096
  patch_size: 256
  mini_patch_size: 16
  pretrain_vit_patch:
  freeze_vit_patch: True
  freeze_vit_patch_pos_embed: True
  mask_attn_patch: False
  num_register_tokens_patch: 0
  pretrain_vit_region:
  img_size_pretrained: ${model.region_size}
  freeze_vit_region: True
  freeze_vit_region_pos_embed: True
  mask_attn_region: False
  num_register_tokens_region: 0
  agg_method: 'concat'
  nfeats_max:
  slide_pos_embed:
    use: False
    learned:
    type:
    max_seq_len:
    max_nslide:
    tile_size:

speed:
  num_workers: 8

resume_id:
wandb:
  enable: False
  project: 'hipt'
  username: 'clemsg'
  exp_name: '${experiment_name}'
  tags:
  dir: '/home/user'
  to_log:
    - 'train': ['loss', 'c-index']
    - 'tune': ['loss', 'c-index']
    - 'test': ['c-index']
  group:

hydra:
  run:
    dir: /tmp/hydra_output